## AIgenerated v/s Human-generated text Classifier Using LSTM

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('FullDataset/final_dataset.csv')

In [3]:
df.head()

id                                            content  label
0   1  Electromagnetic fields (EMFs) are invisible li...      1
1   2  Cryptosporidium infection in acquired immunode...      0
2   3   In today's world, it is not uncommon to see p...      1
3   4  Tension pneumopericardium as a complication of...      0
4   5  Urgent care center pediatric telephone advice....      0

In [4]:
###Drop Nan Values
df=df.dropna()


In [5]:
## Get the Independent Features

X=df.drop(['label','id'],axis=1)

In [6]:
## Get the Dependent features
y=df['label']

In [7]:
X.shape

(23047, 1)

In [8]:
y.shape

(23047,)

In [9]:
import tensorflow as tf

In [10]:
tf.__version__

'2.12.0'

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [12]:
### Vocabulary size
voc_size=10000

### Onehot Representation

In [13]:
messages=X.copy()

In [14]:
messages['content'][1]

'Cryptosporidium infection in acquired immunodeficiency syndrome: not always a poor prognosis. Chronic diarrhea and malabsorption accompanied by simultaneous infection with the protozoa Giardia lamblia and Cryptosporidium occurred in a 22-year-old homosexual man with antibody to human immunodeficiency virus (HIV). Small bowel biopsy demonstrated total villous atrophy and marked mononuclear infiltration in the lamina propria simulating celiac disease. Treatment with metronidazole resulted in resolution of diarrhea, clearance of parasites, and marked improvement in small bowel histology. Although diarrhea and malabsorption in immunocompromised patients with cryptosporidiosis are regarded as ominous, our patient remained disease free for the next 3 years. Thus, infection with Cryptosporidium in patients with HIV does not always lead to intractable diarrhea or death. '

In [15]:
messages.reset_index(inplace=True)

In [16]:
import nltk
import re
from nltk.corpus import stopwords

In [29]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Krish
[nltk_data]     Naik\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [17]:
### Dataset Preprocessing
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0, len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]', ' ', messages['content'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
27

1865
1866
1867
1868
1869
1870
1871
1872
1873
1874
1875
1876
1877
1878
1879
1880
1881
1882
1883
1884
1885
1886
1887
1888
1889
1890
1891
1892
1893
1894
1895
1896
1897
1898
1899
1900
1901
1902
1903
1904
1905
1906
1907
1908
1909
1910
1911
1912
1913
1914
1915
1916
1917
1918
1919
1920
1921
1922
1923
1924
1925
1926
1927
1928
1929
1930
1931
1932
1933
1934
1935
1936
1937
1938
1939
1940
1941
1942
1943
1944
1945
1946
1947
1948
1949
1950
1951
1952
1953
1954
1955
1956
1957
1958
1959
1960
1961
1962
1963
1964
1965
1966
1967
1968
1969
1970
1971
1972
1973
1974
1975
1976
1977
1978
1979
1980
1981
1982
1983
1984
1985
1986
1987
1988
1989
1990
1991
1992
1993
1994
1995
1996
1997
1998
1999
2000
2001
2002
2003
2004
2005
2006
2007
2008
2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019
2020
2021
2022
2023
2024
2025
2026
2027
2028
2029
2030
2031
2032
2033
2034
2035
2036
2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064


3508
3509
3510
3511
3512
3513
3514
3515
3516
3517
3518
3519
3520
3521
3522
3523
3524
3525
3526
3527
3528
3529
3530
3531
3532
3533
3534
3535
3536
3537
3538
3539
3540
3541
3542
3543
3544
3545
3546
3547
3548
3549
3550
3551
3552
3553
3554
3555
3556
3557
3558
3559
3560
3561
3562
3563
3564
3565
3566
3567
3568
3569
3570
3571
3572
3573
3574
3575
3576
3577
3578
3579
3580
3581
3582
3583
3584
3585
3586
3587
3588
3589
3590
3591
3592
3593
3594
3595
3596
3597
3598
3599
3600
3601
3602
3603
3604
3605
3606
3607
3608
3609
3610
3611
3612
3613
3614
3615
3616
3617
3618
3619
3620
3621
3622
3623
3624
3625
3626
3627
3628
3629
3630
3631
3632
3633
3634
3635
3636
3637
3638
3639
3640
3641
3642
3643
3644
3645
3646
3647
3648
3649
3650
3651
3652
3653
3654
3655
3656
3657
3658
3659
3660
3661
3662
3663
3664
3665
3666
3667
3668
3669
3670
3671
3672
3673
3674
3675
3676
3677
3678
3679
3680
3681
3682
3683
3684
3685
3686
3687
3688
3689
3690
3691
3692
3693
3694
3695
3696
3697
3698
3699
3700
3701
3702
3703
3704
3705
3706
3707


5149
5150
5151
5152
5153
5154
5155
5156
5157
5158
5159
5160
5161
5162
5163
5164
5165
5166
5167
5168
5169
5170
5171
5172
5173
5174
5175
5176
5177
5178
5179
5180
5181
5182
5183
5184
5185
5186
5187
5188
5189
5190
5191
5192
5193
5194
5195
5196
5197
5198
5199
5200
5201
5202
5203
5204
5205
5206
5207
5208
5209
5210
5211
5212
5213
5214
5215
5216
5217
5218
5219
5220
5221
5222
5223
5224
5225
5226
5227
5228
5229
5230
5231
5232
5233
5234
5235
5236
5237
5238
5239
5240
5241
5242
5243
5244
5245
5246
5247
5248
5249
5250
5251
5252
5253
5254
5255
5256
5257
5258
5259
5260
5261
5262
5263
5264
5265
5266
5267
5268
5269
5270
5271
5272
5273
5274
5275
5276
5277
5278
5279
5280
5281
5282
5283
5284
5285
5286
5287
5288
5289
5290
5291
5292
5293
5294
5295
5296
5297
5298
5299
5300
5301
5302
5303
5304
5305
5306
5307
5308
5309
5310
5311
5312
5313
5314
5315
5316
5317
5318
5319
5320
5321
5322
5323
5324
5325
5326
5327
5328
5329
5330
5331
5332
5333
5334
5335
5336
5337
5338
5339
5340
5341
5342
5343
5344
5345
5346
5347
5348


6789
6790
6791
6792
6793
6794
6795
6796
6797
6798
6799
6800
6801
6802
6803
6804
6805
6806
6807
6808
6809
6810
6811
6812
6813
6814
6815
6816
6817
6818
6819
6820
6821
6822
6823
6824
6825
6826
6827
6828
6829
6830
6831
6832
6833
6834
6835
6836
6837
6838
6839
6840
6841
6842
6843
6844
6845
6846
6847
6848
6849
6850
6851
6852
6853
6854
6855
6856
6857
6858
6859
6860
6861
6862
6863
6864
6865
6866
6867
6868
6869
6870
6871
6872
6873
6874
6875
6876
6877
6878
6879
6880
6881
6882
6883
6884
6885
6886
6887
6888
6889
6890
6891
6892
6893
6894
6895
6896
6897
6898
6899
6900
6901
6902
6903
6904
6905
6906
6907
6908
6909
6910
6911
6912
6913
6914
6915
6916
6917
6918
6919
6920
6921
6922
6923
6924
6925
6926
6927
6928
6929
6930
6931
6932
6933
6934
6935
6936
6937
6938
6939
6940
6941
6942
6943
6944
6945
6946
6947
6948
6949
6950
6951
6952
6953
6954
6955
6956
6957
6958
6959
6960
6961
6962
6963
6964
6965
6966
6967
6968
6969
6970
6971
6972
6973
6974
6975
6976
6977
6978
6979
6980
6981
6982
6983
6984
6985
6986
6987
6988


8431
8432
8433
8434
8435
8436
8437
8438
8439
8440
8441
8442
8443
8444
8445
8446
8447
8448
8449
8450
8451
8452
8453
8454
8455
8456
8457
8458
8459
8460
8461
8462
8463
8464
8465
8466
8467
8468
8469
8470
8471
8472
8473
8474
8475
8476
8477
8478
8479
8480
8481
8482
8483
8484
8485
8486
8487
8488
8489
8490
8491
8492
8493
8494
8495
8496
8497
8498
8499
8500
8501
8502
8503
8504
8505
8506
8507
8508
8509
8510
8511
8512
8513
8514
8515
8516
8517
8518
8519
8520
8521
8522
8523
8524
8525
8526
8527
8528
8529
8530
8531
8532
8533
8534
8535
8536
8537
8538
8539
8540
8541
8542
8543
8544
8545
8546
8547
8548
8549
8550
8551
8552
8553
8554
8555
8556
8557
8558
8559
8560
8561
8562
8563
8564
8565
8566
8567
8568
8569
8570
8571
8572
8573
8574
8575
8576
8577
8578
8579
8580
8581
8582
8583
8584
8585
8586
8587
8588
8589
8590
8591
8592
8593
8594
8595
8596
8597
8598
8599
8600
8601
8602
8603
8604
8605
8606
8607
8608
8609
8610
8611
8612
8613
8614
8615
8616
8617
8618
8619
8620
8621
8622
8623
8624
8625
8626
8627
8628
8629
8630


10058
10059
10060
10061
10062
10063
10064
10065
10066
10067
10068
10069
10070
10071
10072
10073
10074
10075
10076
10077
10078
10079
10080
10081
10082
10083
10084
10085
10086
10087
10088
10089
10090
10091
10092
10093
10094
10095
10096
10097
10098
10099
10100
10101
10102
10103
10104
10105
10106
10107
10108
10109
10110
10111
10112
10113
10114
10115
10116
10117
10118
10119
10120
10121
10122
10123
10124
10125
10126
10127
10128
10129
10130
10131
10132
10133
10134
10135
10136
10137
10138
10139
10140
10141
10142
10143
10144
10145
10146
10147
10148
10149
10150
10151
10152
10153
10154
10155
10156
10157
10158
10159
10160
10161
10162
10163
10164
10165
10166
10167
10168
10169
10170
10171
10172
10173
10174
10175
10176
10177
10178
10179
10180
10181
10182
10183
10184
10185
10186
10187
10188
10189
10190
10191
10192
10193
10194
10195
10196
10197
10198
10199
10200
10201
10202
10203
10204
10205
10206
10207
10208
10209
10210
10211
10212
10213
10214
10215
10216
10217
10218
10219
10220
10221
10222
10223
1022

11426
11427
11428
11429
11430
11431
11432
11433
11434
11435
11436
11437
11438
11439
11440
11441
11442
11443
11444
11445
11446
11447
11448
11449
11450
11451
11452
11453
11454
11455
11456
11457
11458
11459
11460
11461
11462
11463
11464
11465
11466
11467
11468
11469
11470
11471
11472
11473
11474
11475
11476
11477
11478
11479
11480
11481
11482
11483
11484
11485
11486
11487
11488
11489
11490
11491
11492
11493
11494
11495
11496
11497
11498
11499
11500
11501
11502
11503
11504
11505
11506
11507
11508
11509
11510
11511
11512
11513
11514
11515
11516
11517
11518
11519
11520
11521
11522
11523
11524
11525
11526
11527
11528
11529
11530
11531
11532
11533
11534
11535
11536
11537
11538
11539
11540
11541
11542
11543
11544
11545
11546
11547
11548
11549
11550
11551
11552
11553
11554
11555
11556
11557
11558
11559
11560
11561
11562
11563
11564
11565
11566
11567
11568
11569
11570
11571
11572
11573
11574
11575
11576
11577
11578
11579
11580
11581
11582
11583
11584
11585
11586
11587
11588
11589
11590
11591
1159

12797
12798
12799
12800
12801
12802
12803
12804
12805
12806
12807
12808
12809
12810
12811
12812
12813
12814
12815
12816
12817
12818
12819
12820
12821
12822
12823
12824
12825
12826
12827
12828
12829
12830
12831
12832
12833
12834
12835
12836
12837
12838
12839
12840
12841
12842
12843
12844
12845
12846
12847
12848
12849
12850
12851
12852
12853
12854
12855
12856
12857
12858
12859
12860
12861
12862
12863
12864
12865
12866
12867
12868
12869
12870
12871
12872
12873
12874
12875
12876
12877
12878
12879
12880
12881
12882
12883
12884
12885
12886
12887
12888
12889
12890
12891
12892
12893
12894
12895
12896
12897
12898
12899
12900
12901
12902
12903
12904
12905
12906
12907
12908
12909
12910
12911
12912
12913
12914
12915
12916
12917
12918
12919
12920
12921
12922
12923
12924
12925
12926
12927
12928
12929
12930
12931
12932
12933
12934
12935
12936
12937
12938
12939
12940
12941
12942
12943
12944
12945
12946
12947
12948
12949
12950
12951
12952
12953
12954
12955
12956
12957
12958
12959
12960
12961
12962
1296

14164
14165
14166
14167
14168
14169
14170
14171
14172
14173
14174
14175
14176
14177
14178
14179
14180
14181
14182
14183
14184
14185
14186
14187
14188
14189
14190
14191
14192
14193
14194
14195
14196
14197
14198
14199
14200
14201
14202
14203
14204
14205
14206
14207
14208
14209
14210
14211
14212
14213
14214
14215
14216
14217
14218
14219
14220
14221
14222
14223
14224
14225
14226
14227
14228
14229
14230
14231
14232
14233
14234
14235
14236
14237
14238
14239
14240
14241
14242
14243
14244
14245
14246
14247
14248
14249
14250
14251
14252
14253
14254
14255
14256
14257
14258
14259
14260
14261
14262
14263
14264
14265
14266
14267
14268
14269
14270
14271
14272
14273
14274
14275
14276
14277
14278
14279
14280
14281
14282
14283
14284
14285
14286
14287
14288
14289
14290
14291
14292
14293
14294
14295
14296
14297
14298
14299
14300
14301
14302
14303
14304
14305
14306
14307
14308
14309
14310
14311
14312
14313
14314
14315
14316
14317
14318
14319
14320
14321
14322
14323
14324
14325
14326
14327
14328
14329
1433

15530
15531
15532
15533
15534
15535
15536
15537
15538
15539
15540
15541
15542
15543
15544
15545
15546
15547
15548
15549
15550
15551
15552
15553
15554
15555
15556
15557
15558
15559
15560
15561
15562
15563
15564
15565
15566
15567
15568
15569
15570
15571
15572
15573
15574
15575
15576
15577
15578
15579
15580
15581
15582
15583
15584
15585
15586
15587
15588
15589
15590
15591
15592
15593
15594
15595
15596
15597
15598
15599
15600
15601
15602
15603
15604
15605
15606
15607
15608
15609
15610
15611
15612
15613
15614
15615
15616
15617
15618
15619
15620
15621
15622
15623
15624
15625
15626
15627
15628
15629
15630
15631
15632
15633
15634
15635
15636
15637
15638
15639
15640
15641
15642
15643
15644
15645
15646
15647
15648
15649
15650
15651
15652
15653
15654
15655
15656
15657
15658
15659
15660
15661
15662
15663
15664
15665
15666
15667
15668
15669
15670
15671
15672
15673
15674
15675
15676
15677
15678
15679
15680
15681
15682
15683
15684
15685
15686
15687
15688
15689
15690
15691
15692
15693
15694
15695
1569

16899
16900
16901
16902
16903
16904
16905
16906
16907
16908
16909
16910
16911
16912
16913
16914
16915
16916
16917
16918
16919
16920
16921
16922
16923
16924
16925
16926
16927
16928
16929
16930
16931
16932
16933
16934
16935
16936
16937
16938
16939
16940
16941
16942
16943
16944
16945
16946
16947
16948
16949
16950
16951
16952
16953
16954
16955
16956
16957
16958
16959
16960
16961
16962
16963
16964
16965
16966
16967
16968
16969
16970
16971
16972
16973
16974
16975
16976
16977
16978
16979
16980
16981
16982
16983
16984
16985
16986
16987
16988
16989
16990
16991
16992
16993
16994
16995
16996
16997
16998
16999
17000
17001
17002
17003
17004
17005
17006
17007
17008
17009
17010
17011
17012
17013
17014
17015
17016
17017
17018
17019
17020
17021
17022
17023
17024
17025
17026
17027
17028
17029
17030
17031
17032
17033
17034
17035
17036
17037
17038
17039
17040
17041
17042
17043
17044
17045
17046
17047
17048
17049
17050
17051
17052
17053
17054
17055
17056
17057
17058
17059
17060
17061
17062
17063
17064
1706

18267
18268
18269
18270
18271
18272
18273
18274
18275
18276
18277
18278
18279
18280
18281
18282
18283
18284
18285
18286
18287
18288
18289
18290
18291
18292
18293
18294
18295
18296
18297
18298
18299
18300
18301
18302
18303
18304
18305
18306
18307
18308
18309
18310
18311
18312
18313
18314
18315
18316
18317
18318
18319
18320
18321
18322
18323
18324
18325
18326
18327
18328
18329
18330
18331
18332
18333
18334
18335
18336
18337
18338
18339
18340
18341
18342
18343
18344
18345
18346
18347
18348
18349
18350
18351
18352
18353
18354
18355
18356
18357
18358
18359
18360
18361
18362
18363
18364
18365
18366
18367
18368
18369
18370
18371
18372
18373
18374
18375
18376
18377
18378
18379
18380
18381
18382
18383
18384
18385
18386
18387
18388
18389
18390
18391
18392
18393
18394
18395
18396
18397
18398
18399
18400
18401
18402
18403
18404
18405
18406
18407
18408
18409
18410
18411
18412
18413
18414
18415
18416
18417
18418
18419
18420
18421
18422
18423
18424
18425
18426
18427
18428
18429
18430
18431
18432
1843

19635
19636
19637
19638
19639
19640
19641
19642
19643
19644
19645
19646
19647
19648
19649
19650
19651
19652
19653
19654
19655
19656
19657
19658
19659
19660
19661
19662
19663
19664
19665
19666
19667
19668
19669
19670
19671
19672
19673
19674
19675
19676
19677
19678
19679
19680
19681
19682
19683
19684
19685
19686
19687
19688
19689
19690
19691
19692
19693
19694
19695
19696
19697
19698
19699
19700
19701
19702
19703
19704
19705
19706
19707
19708
19709
19710
19711
19712
19713
19714
19715
19716
19717
19718
19719
19720
19721
19722
19723
19724
19725
19726
19727
19728
19729
19730
19731
19732
19733
19734
19735
19736
19737
19738
19739
19740
19741
19742
19743
19744
19745
19746
19747
19748
19749
19750
19751
19752
19753
19754
19755
19756
19757
19758
19759
19760
19761
19762
19763
19764
19765
19766
19767
19768
19769
19770
19771
19772
19773
19774
19775
19776
19777
19778
19779
19780
19781
19782
19783
19784
19785
19786
19787
19788
19789
19790
19791
19792
19793
19794
19795
19796
19797
19798
19799
19800
1980

21003
21004
21005
21006
21007
21008
21009
21010
21011
21012
21013
21014
21015
21016
21017
21018
21019
21020
21021
21022
21023
21024
21025
21026
21027
21028
21029
21030
21031
21032
21033
21034
21035
21036
21037
21038
21039
21040
21041
21042
21043
21044
21045
21046
21047
21048
21049
21050
21051
21052
21053
21054
21055
21056
21057
21058
21059
21060
21061
21062
21063
21064
21065
21066
21067
21068
21069
21070
21071
21072
21073
21074
21075
21076
21077
21078
21079
21080
21081
21082
21083
21084
21085
21086
21087
21088
21089
21090
21091
21092
21093
21094
21095
21096
21097
21098
21099
21100
21101
21102
21103
21104
21105
21106
21107
21108
21109
21110
21111
21112
21113
21114
21115
21116
21117
21118
21119
21120
21121
21122
21123
21124
21125
21126
21127
21128
21129
21130
21131
21132
21133
21134
21135
21136
21137
21138
21139
21140
21141
21142
21143
21144
21145
21146
21147
21148
21149
21150
21151
21152
21153
21154
21155
21156
21157
21158
21159
21160
21161
21162
21163
21164
21165
21166
21167
21168
2116

22372
22373
22374
22375
22376
22377
22378
22379
22380
22381
22382
22383
22384
22385
22386
22387
22388
22389
22390
22391
22392
22393
22394
22395
22396
22397
22398
22399
22400
22401
22402
22403
22404
22405
22406
22407
22408
22409
22410
22411
22412
22413
22414
22415
22416
22417
22418
22419
22420
22421
22422
22423
22424
22425
22426
22427
22428
22429
22430
22431
22432
22433
22434
22435
22436
22437
22438
22439
22440
22441
22442
22443
22444
22445
22446
22447
22448
22449
22450
22451
22452
22453
22454
22455
22456
22457
22458
22459
22460
22461
22462
22463
22464
22465
22466
22467
22468
22469
22470
22471
22472
22473
22474
22475
22476
22477
22478
22479
22480
22481
22482
22483
22484
22485
22486
22487
22488
22489
22490
22491
22492
22493
22494
22495
22496
22497
22498
22499
22500
22501
22502
22503
22504
22505
22506
22507
22508
22509
22510
22511
22512
22513
22514
22515
22516
22517
22518
22519
22520
22521
22522
22523
22524
22525
22526
22527
22528
22529
22530
22531
22532
22533
22534
22535
22536
22537
2253

In [18]:
corpus

['electromagnet field emf invis line energi creat electr current flow wire emf around us constantli expos varieti sourc includ cell phone wireless devic power line electr applianc microwav oven fluoresc light potenti health effect emf exposur subject much research definit answer whether harm studi suggest emf exposur may link increas risk certain health problem cancer other found evid harm effect research need determin whether link emf exposur cognit function studi shown emf exposur may associ chang brain activ clear whether chang harm addit studi shown emf exposur may associ increas risk certain cognit problem memori loss attent problem studi found evid harm effect time evid emf exposur everyday sourc pose signific risk cognit function brain health howev research need determin whether long term effect exposur high level emf concern potenti health effect emf exposur take step reduc exposur use hand free devic talk cell phone keep cell phone away bodi use unplug applianc use',
 'cryptos

In [19]:
onehot_repr=[one_hot(words,voc_size)for words in corpus] 
onehot_repr

[[6007,
  9634,
  5224,
  2890,
  8145,
  357,
  7370,
  1305,
  6448,
  3397,
  4413,
  5224,
  4211,
  5061,
  4254,
  6230,
  2120,
  7237,
  2312,
  993,
  1761,
  9386,
  4565,
  3475,
  8145,
  1305,
  5970,
  7314,
  649,
  8041,
  9396,
  2668,
  9936,
  686,
  5224,
  5352,
  7566,
  7032,
  2636,
  3033,
  6664,
  5189,
  7090,
  9662,
  3305,
  5224,
  5352,
  9327,
  2526,
  6578,
  2155,
  2153,
  9936,
  5537,
  6940,
  4783,
  7482,
  1145,
  7090,
  686,
  2636,
  5030,
  4857,
  5189,
  2526,
  5224,
  5352,
  9497,
  3866,
  9662,
  7203,
  5224,
  5352,
  9327,
  2199,
  608,
  8952,
  5761,
  5221,
  5189,
  608,
  7090,
  8281,
  9662,
  7203,
  5224,
  5352,
  9327,
  2199,
  6578,
  2155,
  2153,
  9497,
  5537,
  7674,
  6408,
  70,
  5537,
  9662,
  7482,
  1145,
  7090,
  686,
  2632,
  1145,
  5224,
  5352,
  4966,
  7237,
  2087,
  6570,
  2155,
  9497,
  3866,
  8952,
  9936,
  9435,
  2636,
  5030,
  4857,
  5189,
  7250,
  811,
  686,
  5352,
  2205,
  70

In [21]:
import numpy as np

# Convert to numpy array for easier handling
one_hot_sentences = np.array(onehot_repr, dtype=object)

# Calculate the length of each sentence
sentence_lengths = np.array([len(sentence) for sentence in one_hot_sentences])

# Find the length of the longest sentence
max_length = np.max(sentence_lengths)

print("One-Hot Sentences:")
print(one_hot_sentences)
print("\nSentence Lengths:")
print(sentence_lengths)
print("\nLength of Longest Sentence:", max_length)


One-Hot Sentences:
[list([6007, 9634, 5224, 2890, 8145, 357, 7370, 1305, 6448, 3397, 4413, 5224, 4211, 5061, 4254, 6230, 2120, 7237, 2312, 993, 1761, 9386, 4565, 3475, 8145, 1305, 5970, 7314, 649, 8041, 9396, 2668, 9936, 686, 5224, 5352, 7566, 7032, 2636, 3033, 6664, 5189, 7090, 9662, 3305, 5224, 5352, 9327, 2526, 6578, 2155, 2153, 9936, 5537, 6940, 4783, 7482, 1145, 7090, 686, 2636, 5030, 4857, 5189, 2526, 5224, 5352, 9497, 3866, 9662, 7203, 5224, 5352, 9327, 2199, 608, 8952, 5761, 5221, 5189, 608, 7090, 8281, 9662, 7203, 5224, 5352, 9327, 2199, 6578, 2155, 2153, 9497, 5537, 7674, 6408, 70, 5537, 9662, 7482, 1145, 7090, 686, 2632, 1145, 5224, 5352, 4966, 7237, 2087, 6570, 2155, 9497, 3866, 8952, 9936, 9435, 2636, 5030, 4857, 5189, 7250, 811, 686, 5352, 2205, 7082, 5224, 7669, 2668, 9936, 686, 5224, 5352, 5856, 2078, 5309, 5352, 6953, 4915, 8989, 4565, 2977, 993, 1761, 2339, 993, 1761, 6603, 1278, 6953, 9367, 5970, 6953])
 list([9287, 8286, 5773, 15, 421, 918, 5406, 2554, 6909, 2858, 9

### Embedding Representation

In [22]:
sent_length=480
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 ... 9367 5970 6953]
 [   0    0    0 ... 6315 2858 4199]
 [   0    0    0 ... 7504 5313 7458]
 ...
 [   0    0    0 ... 2092 2597 5853]
 [   0    0    0 ... 4341 6983 1381]
 [   0    0    0 ...    3 5083 1256]]


In [23]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [78]:
## Creating model
'''embedding_vector_features=100
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())'''

from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=50
model=Sequential()
model.add(Embedding(voc_size,embedding_vector_features,input_length=sent_length))
model.add(Dropout(0.3))
model.add(LSTM(25))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_5 (Embedding)     (None, 480, 50)           500000    
                                                                 
 dropout_8 (Dropout)         (None, 480, 50)           0         
                                                                 
 lstm_5 (LSTM)               (None, 25)                7600      
                                                                 
 dropout_9 (Dropout)         (None, 25)                0         
                                                                 
 dense_5 (Dense)             (None, 1)                 26        
                                                                 
Total params: 507,626
Trainable params: 507,626
Non-trainable params: 0
_________________________________________________________________
None


In [79]:
len(embedded_docs),y.shape

(23047, (23047,))

In [80]:
import numpy as np
X_final=np.array(embedded_docs)
y_final=np.array(y)

In [81]:
X_final.shape,y_final.shape

((23047, 480), (23047,))

In [82]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_final, y_final, test_size=0.20, random_state=42)

### Model Training

In [83]:
### Finally Training
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss', patience=2, restore_best_weights=True)
model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=10,batch_size=64, callbacks=[early_stopping])

Epoch 1/10
289/289 [==============================] - 64s 212ms/step - loss: 0.2495 - accuracy: 0.9369 - val_loss: 0.0489 - val_accuracy: 0.9922
Epoch 2/10
289/289 [==============================] - 60s 207ms/step - loss: 0.0319 - accuracy: 0.9951 - val_loss: 0.0276 - val_accuracy: 0.9939
Epoch 3/10
289/289 [==============================] - 72s 248ms/step - loss: 0.0164 - accuracy: 0.9979 - val_loss: 0.0248 - val_accuracy: 0.9939
Epoch 4/10
289/289 [==============================] - 74s 256ms/step - loss: 0.0086 - accuracy: 0.9988 - val_loss: 0.0146 - val_accuracy: 0.9963
Epoch 5/10
289/289 [==============================] - 72s 248ms/step - loss: 0.0048 - accuracy: 0.9993 - val_loss: 0.0353 - val_accuracy: 0.9911
Epoch 6/10
289/289 [==============================] - 75s 259ms/step - loss: 0.0033 - accuracy: 0.9995 - val_loss: 0.0272 - val_accuracy: 0.9928


In [84]:
# Save the trained model
model.save('lstm_4.h5')

### Performance Metrics And Accuracy

In [85]:
from sklearn.metrics import confusion_matrix, classification_report

# Evaluate the model on test data
loss, accuracy = model.evaluate(X_test, y_test)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

# Get predictions
y_pred = (model.predict(X_test) > 0.5).astype("int32")

# Confusion Matrix
conf_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(conf_matrix)

# Classification Report
class_report = classification_report(y_test, y_pred)
print("Classification Report:")
print(class_report)

145/145 [==============================] - 6s 41ms/step - loss: 0.0146 - accuracy: 0.9963
Test Loss: 0.014642560854554176
Test Accuracy: 0.9963123798370361
145/145 [==============================] - 7s 47ms/step
Confusion Matrix:
[[2333    7]
 [  10 2260]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      2340
           1       1.00      1.00      1.00      2270

    accuracy                           1.00      4610
   macro avg       1.00      1.00      1.00      4610
weighted avg       1.00      1.00      1.00      4610



In [ ]:
''' Human genrated:
1. Dental fluorosis is a cosmetic condition that often raises concerns among parents and individuals, yet it does not pose a threat to the overall health of teeth. It occurs when excessive fluoride is consumed during the formation of 'adult' teeth, typically between the ages of 3 months to 8 years. Once teeth have erupted through the gums, the risk of developing fluorosis diminishes. In her latest online article, Dr Anne Gormley gives us her insights.
2. The consistent overconsumption of sodium across the socioeconomic spectrum suggests that factors beyond just access to resources may influence sodium intake





AI generated:
1. Fever, often a sign of infection, can be managed at home with rest, hydration, and fever-reducing medications like acetaminophen or ibuprofen. Use cooling measures like damp cloths to reduce discomfort. Monitor your temperature and seek medical help if it persists, especially if it's very high, or if you have severe symptoms like difficulty breathing or confusion. Prevent spread by practicing good hygiene. For severe or persistent fever, prompt medical attention is advised.
2. 


'''


In [92]:
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
import re
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Sample single text input
single_text = "The consistent overconsumption of sodium across the socioeconomic spectrum suggests that factors beyond just access to resources may influence sodium intake"

# Initialize Porter Stemmer and load English stopwords
ps = PorterStemmer()
stop_words = set(stopwords.words('english'))

# Text preprocessing function
def preprocess_text(text):
    # Remove non-alphabetic characters
    text = re.sub('[^a-zA-Z]', ' ', text)
    # Convert to lowercase
    text = text.lower()
    # Tokenize
    words = text.split()
    # Stemming and remove stopwords
    stemmed_words = [ps.stem(word) for word in words if word not in stop_words]
    # Join the words back
    processed_text = ' '.join(stemmed_words)
    return processed_text

# Preprocess the single text input
processed_single_text = preprocess_text(single_text)
print("Processed Text:", processed_single_text)

# Convert to one-hot representation
single_onehot_repr = [one_hot(processed_single_text, voc_size)]
print("One-Hot Representation:", single_onehot_repr)

# Pad sequences to the same length
single_padded_text = pad_sequences(single_onehot_repr, padding='pre', maxlen=sent_length)
print("Padded Text:")
print(single_padded_text)


Processed Text: consist overconsumpt sodium across socioeconom spectrum suggest factor beyond access resourc may influenc sodium intak
One-Hot Representation: [[6355, 2570, 4710, 6209, 297, 4681, 3305, 4812, 2147, 5788, 7603, 9327, 3320, 4710, 5137]]
Padded Text:
[[   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0

In [93]:
prediction = (model.predict(single_padded_text) > 0.5).astype("int32")

# Decode the prediction
label = "AI Generated" if prediction[0][0] == 1 else "Human Generated"
print("Predicted Label:", label)

1/1 [==============================] - 0s 100ms/step
Predicted Label: Human Generated
